name: Run SonarQube Scan Github Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.5
      env:
        GIT_HUB_PERSONAL_TOKEN: ${{ secrets.GIT_HUB_PERSONAL_TOKEN }}
        SONAR_TOKEN: ${{ SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization-swaraj1.sys
          -Dsonar.projectKey-SonarCloudCodeAnalysis
          -Dsonar.python.coverage.reportPaths=coverage.xml
